version: '2'
services:
    elk-elasticsearch:
        build: jhipster-elasticsearch/ 
        ports:
            - "9200:9200"
            - "9300:9300"
        # Uncomment this section to have elasticsearch data loaded from a volume
        #volumes:
        #   - ./log-data:/usr/share/elasticsearch/data

    elk-logstash:
        build: jhipster-logstash/
        # Uncomment to have logstash config loaded from a volume
        #volumes:
        #    - ./jhipster-logstash/conf/:/conf
        command: logstash -f /conf/logstash.conf
        ports:
            - "5000:5000/udp"
    jhipster-console:
        build: jhipster-console/
        ports:
            - "5601:5601"
        # Uncomment this section to have kibana JSON files loaded from a volume
        #volumes:
        #    - ./jhipster-console/dashboards:/tmp/dashboards

    jhipster-alerter:
        build: jhipster-alerter/
        environment:
            - ENABLE_ALERTING=true
        # uncomment this section to enable alerting
        #volumes:
        #    - ./alerts/config.yaml:/opt/elastalert/config.yaml
        #    - ./alerts/rules/:/opt/elastalert/rules
